export const protonSuites = [
  {
    id: 'protonInbound',
    eyebrow: 'PROTON INBOUND',
    title: '入库套件',
    desc: '覆盖采购、ASN、收货、退货入库和 OMS 入库协同',
    primary: '生成收货任务',
    modules: [
      { name: '采购订单', route: '/ibdPo/list', object: 'PO260710-001', actions: ['创建采购入库源单', '确认到货计划', '关闭采购订单'], api: '/proton/ibdPo/list' },
      { name: 'ASN 入库单', route: '/ibdAsn/list', object: 'ASN260710-014', actions: ['预约到货', '确认 ASN', '导入明细', '关闭 ASN'], api: '/proton/ibdAsn/list' },
      { name: 'B2B ASN', route: '/ibdAsnBb/list', object: 'ASN-BB-260710-006', actions: ['批量预约', '托盘收货', 'B2B 上架'], api: '/proton/ibdAsnBb/list' },
      { name: '其他入库 ASN', route: '/ibdAsnOther/list', object: 'ASN-OTH-260710-003', actions: ['无采购入库', '差异登记', '提交审批'], api: '/proton/ibdAsnOther/list' },
      { name: 'ASN 模板', route: '/ibdAsnTpl/list', object: 'TPL-ASN-STD', actions: ['维护导入模板', '字段映射', '模板启停'], api: '/proton/ibdAsnTpl/list' },
      { name: '收货记录', route: '/ibdReceiptRecord/list', object: 'REC260710-024', actions: ['扫描收货', '复核差异', '生成上架任务'], api: '/proton/ibdReceiptRecord/list' },
      { name: 'B2B 收货记录', route: '/ibdReceiptRecordBb/list', object: 'REC-BB-260710-012', actions: ['托盘收货', '批量确认', '回写库存'], api: '/proton/ibdReceiptRecordBb/list' },
      { name: '退货入库', route: '/ibdAsnReturn/list', object: 'RASN260710-008', actions: ['RMA 关联', '质检处置', '良品入库'], api: '/proton/ibdAsnReturn/list' },
      { name: 'FBA 退货', route: '/ibdFbaReturn/list', object: 'FBA-R260710-002', actions: ['箱号校验', '换标入库', '异常隔离'], api: '/proton/ibdFbaReturn/list' },
      { name: 'OMS 入库单', route: '/omsAsn/list', object: 'OMS-ASN-260710-009', actions: ['OMS 同步', '幂等接收', '回传收货结果'], api: '/proton/omsAsn/list' },
    ],
  },
  {
    id: 'protonInventory',
    eyebrow: 'PROTON INVENTORY',
    title: '库存套件',
    desc: '覆盖库存余额、流水、移动、调整、盘点、初始化、图片、预警和 FBA 换标',
    primary: '执行库存事务',
    modules: [
      { name: '库存查询', route: '/invInventory/list', object: 'SKU-AX19-042', actions: ['按仓库查询', '冻结/解冻', '批次追踪'], api: '/proton/invInventory/list' },
      { name: 'B2B 库存', route: '/invInventoryBb/list', object: 'B2B-SKU-019', actions: ['托盘维度查询', '客户库存隔离', '库存导出'], api: '/proton/invInventoryBb/list' },
      { name: '库存汇总', route: '/inventorySummaryB2B/list', object: 'SUM-B2B-260710', actions: ['按客户汇总', '按仓汇总', '差异定位'], api: '/proton/inventorySummaryB2B/list' },
      { name: '库存事务', route: '/invTrasaction/list', object: 'TXN260710-116', actions: ['入账追踪', 'ERP 对账', '事务导出'], api: '/proton/invTrasaction/list' },
      { name: '库内移动', route: '/invMove/list', object: 'MOV260710-018', actions: ['整箱移动', '托盘移动', '按件移动'], api: '/proton/invMove/list' },
      { name: '库存调整', route: '/invAdjust/list', object: 'ADJ260710-004', actions: ['创建调整', '高风险审批', '调整入账'], api: '/proton/invAdjust/list' },
      { name: '批次调整', route: '/invLotAdjust/list', object: 'LOT-ADJ-260710', actions: ['批次更正', '效期更正', '保留审计'], api: '/proton/invLotAdjust/list' },
      { name: '补货需求', route: '/invRepReq/list', object: 'REP260710-021', actions: ['需求计算', '合并下发', '生成补货任务'], api: '/proton/invRepReq/list' },
      { name: '盘点计划', route: '/invCcPlan/list', object: 'CCP260710-003', actions: ['新建计划', '冻结范围', '生成盘点单'], api: '/proton/invCcPlan/list' },
      { name: '盘点单', route: '/InvCc/list', object: 'CC260710-017', actions: ['初盘', '复盘', '生成差异调整'], api: '/proton/InvCc/list' },
      { name: '盘点任务', route: '/ccTask/list', object: 'CCT260710-091', actions: ['任务领取', '扫描盘点', '提交实盘'], api: '/proton/ccTask/list' },
      { name: '盘点任务组', route: '/ccTaskGroup/list', object: 'CCG260710-008', actions: ['分组派工', '进度追踪', '关闭任务组'], api: '/proton/ccTaskGroup/list' },
      { name: '库存初始化', route: '/invInt/list', object: 'INIT260710-001', actions: ['模板导入', '校验差异', '初始化入账'], api: '/proton/invInt/list' },
      { name: 'B2B 初始化', route: '/invInitB2b/list', object: 'B2B-INIT-001', actions: ['客户库存导入', '托盘校验', '初始化确认'], api: '/proton/invInitB2b/list' },
      { name: '库存图片', route: '/invImage/list', object: 'IMG-SKU-AX19', actions: ['上传图片', '关联 SKU/批次', '异常取证'], api: '/proton/invImage/list' },
      { name: '库存预警', route: '/invAlert/list', object: 'ALERT260710-006', actions: ['阈值维护', '自动重算', '生成补货建议'], api: '/proton/invAlert/list' },
      { name: '环境库存', route: '/environmentList/list', object: 'ENV260710-002', actions: ['温湿度绑定', '库存风险提示', '环境记录追踪'], api: '/proton/environmentList/list' },
      { name: 'FBA 换标', route: '/invFbaExchange/list', object: 'FBA-EX260710-005', actions: ['换标申请', '箱明细扫描', '换标完成'], api: '/proton/invFbaExchange/list' },
      { name: '换标箱明细', route: '/fbaExchangeCarton/list', object: 'FBA-CTN-260710', actions: ['箱号扫描', '标签校验', '完成装箱'], api: '/proton/fbaExchangeCarton/list' },
    ],
  },
  {
    id: 'protonOutbound',
    eyebrow: 'PROTON OUTBOUND',
    title: '出库套件',
    desc: '覆盖订单、波次、分拣、复核、装箱、称重、装载和分配失败处理',
    primary: '推进出库流程',
    modules: [
      { name: '销售出库单', route: '/obdShippingOrder/list', object: 'SO260710-032', actions: ['订单校验', '库存分配', '释放作业'], api: '/proton/obdShippingOrder/list' },
      { name: '其他出库单', route: '/obdOtherShippingOrder/list', object: 'OSO260710-004', actions: ['手工出库', '审批校验', '扣减库存'], api: '/proton/obdOtherShippingOrder/list' },
      { name: '预约出库单', route: '/appointShippingOrder/list', object: 'APT260710-011', actions: ['预约确认', '到车登记', '发运交接'], api: '/proton/appointShippingOrder/list' },
      { name: 'OMS 订单', route: '/obdOmsOrder/list', object: 'OMS-SO-260710', actions: ['接收订单', '幂等校验', '状态回传'], api: '/proton/obdOmsOrder/list' },
      { name: 'B2B 出库单', route: '/shippingOrderBb/list', object: 'BB-SO260710-018', actions: ['托盘拣选', '整托复核', '客户交接'], api: '/proton/shippingOrderBb/list' },
      { name: 'FBA 出库单', route: '/shippingOrderFba/list', object: 'FBA-SO260710-007', actions: ['箱唛校验', 'FBA 装箱', '发运确认'], api: '/proton/shippingOrderFba/list' },
      { name: '波次管理', route: '/obdWave/list', object: 'WV260710-009', actions: ['规则试算', '释放波次', '生成拣货任务'], api: '/proton/obdWave/list' },
      { name: '二次分拣', route: '/obdTwoSorting/list', object: 'SORT260710-016', actions: ['播种扫描', '格口校验', '完成分拣'], api: '/proton/obdTwoSorting/list' },
      { name: '订单复核', route: '/obdOrderCheck/list', object: 'CHK260710-039', actions: ['扫描复核', '差异拦截', '复核完成'], api: '/proton/obdOrderCheck/list' },
      { name: '装箱管理', route: '/obdOrderCarton/list', object: 'CTN260710-088', actions: ['箱规选择', '装箱确认', '打印箱唛'], api: '/proton/obdOrderCarton/list' },
      { name: '称重管理', route: '/obdOrderWeight/list', object: 'WGT260710-066', actions: ['称重采集', '差异校验', '放行包装'], api: '/proton/obdOrderWeight/list' },
      { name: '装载管理', route: '/obdLoading/list', object: 'LOAD260710-012', actions: ['月台分配', '扫描装车', '承运交接'], api: '/proton/obdLoading/list' },
      { name: '装载扫描', route: '/obdLoading/scan', object: 'LOAD-SCAN-260710', actions: ['运单扫描', '箱号校验', '完成装车'], api: '/proton/obdLoading/scan' },
      { name: 'B2B 装载', route: '/obdLoadingBb/list', object: 'BB-LOAD-260710', actions: ['托盘装车', '车辆校验', 'B2B 交接'], api: '/proton/obdLoadingBb/list' },
      { name: '装载托盘', route: '/loading/loadingPalletlist', object: 'PLT260710-021', actions: ['托盘绑定', '装车复核', '交接确认'], api: '/proton/loading/loadingPalletlist' },
      { name: '大件复核', route: '/obdLargeCheck/largeCheck', object: 'LARGE260710-003', actions: ['大件扫描', '包装检查', '异常拦截'], api: '/proton/obdLargeCheck/largeCheck' },
      { name: '分拣复核', route: '/shippingOrder/sortCheck', object: 'SORTCHK260710', actions: ['格口复核', '订单合流', '异常处理'], api: '/proton/shippingOrder/sortCheck' },
      { name: '拣货确认', route: '/wave/pickTaskConfirmForm', object: 'PICK260710-128', actions: ['任务确认', '短拣上报', '库存扣减预占'], api: '/proton/wave/pickTaskConfirmForm' },
      { name: '分配失败', route: '/obdAllocFail/list', object: 'ALLOC-FAIL-260710', actions: ['失败定位', '补货/释放', '重新分配'], api: '/proton/obdAllocFail/list' },
    ],
  },
  {
    id: 'protonMaster',
    eyebrow: 'PROTON MASTER',
    title: '主数据套件',
    desc: '覆盖仓库库位、商品包装、客户供应商、承运商、海关、车辆和物流区域',
    primary: '同步主数据',
    modules: [
      { name: '仓库管理', route: '/mstWh/list', object: 'WH-SH-01', actions: ['新增仓库', '启停仓库', '同步仓库权限'], api: '/proton/mstWh/list' },
      { name: '库区管理', route: '/mstZone/list', object: 'ZONE-A', actions: ['维护库区', '绑定作业类型', '容量校验'], api: '/proton/mstZone/list' },
      { name: '库位管理', route: '/mstLocation/list', object: 'A-01-03-02', actions: ['新增库位', '容量维护', '混放规则校验'], api: '/proton/mstLocation/list' },
      { name: '商品管理', route: '/mstSku/list', object: 'SKU-AX19-042', actions: ['SKU 建档', '批次属性', '状态启停'], api: '/proton/mstSku/list' },
      { name: '商品条码', route: '/mstSkuBarcode/list', object: 'BC-SKU-AX19', actions: ['条码绑定', '唯一性校验', '扫码识别'], api: '/proton/mstSkuBarcode/list' },
      { name: '包装管理', route: '/mstPack/list', object: 'PACK-STD', actions: ['包装建档', '单位换算', '箱规维护'], api: '/proton/mstPack/list' },
      { name: '商品包装', route: '/mstPackSku/list', object: 'PACK-SKU-AX19', actions: ['绑定 SKU', '维护长宽高', '称重校验'], api: '/proton/mstPackSku/list' },
      { name: '商品价格', route: '/mstSkuPrice/list', object: 'PRICE-SKU-AX19', actions: ['价格维护', '计费引用', '版本生效'], api: '/proton/mstSkuPrice/list' },
      { name: '仓库商品', route: '/mstWhSku/list', object: 'WH-SKU-AX19', actions: ['仓库授权', '库存属性', '上下架控制'], api: '/proton/mstWhSku/list' },
      { name: '仓库商品类型', route: '/mstWhSkuType/list', object: 'WH-SKU-TYPE', actions: ['类型维护', '作业规则绑定', '报表分组'], api: '/proton/mstWhSkuType/list' },
      { name: '客户管理', route: '/mstCustomer/list', object: 'CUS-NEBULA', actions: ['客户建档', '货主绑定', '结算配置'], api: '/proton/mstCustomer/list' },
      { name: '供应商管理', route: '/mstVendor/list', object: 'VEN-STAR', actions: ['供应商建档', '采购来源绑定', '状态控制'], api: '/proton/mstVendor/list' },
      { name: '公司管理', route: '/mstCompany/list', object: 'COMP-HQ', actions: ['组织维护', '租户归属', '财务主体'], api: '/proton/mstCompany/list' },
      { name: '承运商管理', route: '/mstCarrier/list', object: 'CAR-SF', actions: ['承运商建档', '服务范围', '面单模板绑定'], api: '/proton/mstCarrier/list' },
      { name: '海关资料', route: '/mstCustoms/list', object: 'CUSDECL-001', actions: ['申报资料', '品名维护', '跨境校验'], api: '/proton/mstCustoms/list' },
      { name: '车辆管理', route: '/mstVehicle/list', object: '沪A-D2607', actions: ['车辆建档', '司机绑定', '装载预约'], api: '/proton/mstVehicle/list' },
      { name: '批次属性模板', route: '/mstLotAttrTemplate/list', object: 'LOT-TPL-FEFO', actions: ['批次字段', '效期规则', '入库校验'], api: '/proton/mstLotAttrTemplate/list' },
      { name: '物流区域', route: '/logisticRegionInfo/list', object: 'REGION-EAST', actions: ['区域维护', '邮编映射', '路由匹配'], api: '/proton/logisticRegionInfo/list' },
      { name: '区域策略', route: '/logisticRegionStrategy/list', object: 'REGION-STR-001', actions: ['策略配置', '优先级校验', '路由试算'], api: '/proton/logisticRegionStrategy/list' },
      { name: '物流费模板', route: '/logisticFeeTemplate/list', object: 'FEE-TPL-STD', actions: ['费用模板', '计费维度', '版本发布'], api: '/proton/logisticFeeTemplate/list' },
    ],
  },
  {
    id: 'protonStrategy',
    eyebrow: 'PROTON STRATEGY',
    title: '策略套件',
    desc: '覆盖分配、上架、波次、质检、效期、条码和物流计费策略',
    primary: '规则试算',
    modules: [
      { name: '分配策略', route: '/strAllocationStrategy/list', object: 'ALLOC-FEFO-B2C', actions: ['策略编辑', '冲突检测', '分配试算'], api: '/proton/strAllocationStrategy/list' },
      { name: '上架策略', route: '/strPutawayStrategy/list', object: 'PUT-AUTO-ZONE', actions: ['库位推荐', '混放控制', '上架试算'], api: '/proton/strPutawayStrategy/list' },
      { name: '波次策略', route: '/strWaveStrategy/list', object: 'WAVE-MORNING', actions: ['截单规则', '产能约束', '波次试算'], api: '/proton/strWaveStrategy/list' },
      { name: '质检策略', route: '/strQualStrategyList/list', object: 'QC-RISK-STD', actions: ['抽检比例', '风险分层', '质检任务生成'], api: '/proton/strQualStrategyList/list' },
      { name: '效期策略', route: '/strShelfLifeStrategy/list', object: 'SHELF-FEFO', actions: ['效期阈值', '临期拦截', '出库校验'], api: '/proton/strShelfLifeStrategy/list' },
      { name: '条码策略', route: '/strBarcodeStrategy/list', object: 'BARCODE-STD', actions: ['条码解析', '扫码规则', '异常拦截'], api: '/proton/strBarcodeStrategy/list' },
      { name: '油费策略', route: '/strFinanceOilStrategy/list', object: 'OIL-FEE-001', actions: ['油费规则', '线路匹配', '计费试算'], api: '/proton/strFinanceOilStrategy/list' },
      { name: '超规策略', route: '/strFinanceOversizeStrategy/list', object: 'OVERSIZE-001', actions: ['超长超重', '费用加收', '异常提示'], api: '/proton/strFinanceOversizeStrategy/list' },
      { name: '区域计费策略', route: '/strFinanceRegionStrategy/list', object: 'REG-FEE-001', actions: ['区域匹配', '首续重', '费用试算'], api: '/proton/strFinanceRegionStrategy/list' },
      { name: '偏远地区策略', route: '/strFinanceRemoteAreaStrategy/list', object: 'REMOTE-001', actions: ['偏远识别', '附加费', '报价生效'], api: '/proton/strFinanceRemoteAreaStrategy/list' },
      { name: '物流计费模板', route: '/strFinanceLogisticFeeTemplateList/list', object: 'LOG-FEE-TPL', actions: ['模板维护', '策略引用', '版本发布'], api: '/proton/strFinanceLogisticFeeTemplateList/list' },
    ],
  },
  {
    id: 'protonFinance',
    eyebrow: 'PROTON FINANCE',
    title: '计费财务套件',
    desc: '覆盖报价、充值、账单和调整账单',
    primary: '生成计费结果',
    modules: [
      { name: '操作报价', route: '/quotation/operate', object: 'QUO-OP-260710', actions: ['操作费报价', '阶梯计价', '报价生效'], api: '/proton/quotation/operate' },
      { name: '服务报价', route: '/quotation/service', object: 'QUO-SVC-260710', actions: ['服务项维护', '客户报价', '版本发布'], api: '/proton/quotation/service' },
      { name: '仓租报价', route: '/quotation/whRent', object: 'QUO-RENT-260710', actions: ['仓租维度', '面积/托盘计价', '报价试算'], api: '/proton/quotation/whRent' },
      { name: '报价单列表', route: '/quotation/whQuotationList', object: 'QUO-LIST-260710', actions: ['报价查询', '审批发布', '客户生效'], api: '/proton/quotation/whQuotationList' },
      { name: '账户充值', route: '/recharge/list', object: 'RECH260710-002', actions: ['充值登记', '余额更新', '财务审核'], api: '/proton/recharge/list' },
      { name: '费用账单', route: '/financeBill/list', object: 'BILL260710-009', actions: ['账单生成', '明细核对', '确认账单'], api: '/proton/financeBill/list' },
      { name: '调整账单', route: '/financeAdjustBill/list', object: 'ABILL260710-003', actions: ['差异调整', '审批确认', '冲销入账'], api: '/proton/financeAdjustBill/list' },
    ],
  },
  {
    id: 'protonReports',
    eyebrow: 'PROTON REPORTS',
    title: '报表套件',
    desc: '覆盖入库、出库、库存进销存、托盘和绩效报表',
    primary: '生成报表',
    modules: [
      { name: 'ASN 入库报表', route: '/ibdAsnReport/list', object: 'RPT-ASN-260710', actions: ['按 ASN 汇总', '收货差异', '导出报表'], api: '/proton/ibdAsnReport/list' },
      { name: 'B2B 入库报表', route: '/inboundReportB2B/list', object: 'RPT-IN-B2B', actions: ['按客户统计', '托盘维度', '导出报表'], api: '/proton/inboundReportB2B/list' },
      { name: '出库报表', route: '/obdOrderReport/list', object: 'RPT-OUT-260710', actions: ['订单履约', '渠道统计', '导出报表'], api: '/proton/obdOrderReport/list' },
      { name: 'B2B 出库报表', route: '/outboundReportB2B/list', object: 'RPT-OUT-B2B', actions: ['客户出库', '托盘交接', '导出报表'], api: '/proton/outboundReportB2B/list' },
      { name: '分配报表', route: '/obdOrderAllocReport/list', object: 'RPT-ALLOC-260710', actions: ['分配成功率', '失败原因', '补货转化'], api: '/proton/obdOrderAllocReport/list' },
      { name: '进销存报表', route: '/inOutInv/list', object: 'RPT-IOI-260710', actions: ['期初期末', '入出调整', '库存结存'], api: '/proton/inOutInv/list' },
      { name: '托盘报表', route: '/palletInfoB2B/list', object: 'RPT-PLT-B2B', actions: ['托盘状态', '库位分布', '客户归属'], api: '/proton/palletInfoB2B/list' },
      { name: '绩效报表', route: '/performanceReport/list', object: 'RPT-PERF-260710', actions: ['人员绩效', '任务耗时', '异常率'], api: '/proton/performanceReport/list' },
    ],
  },
  {
    id: 'protonTask',
    eyebrow: 'PROTON TASK',
    title: '任务集成套件',
    desc: '覆盖作业任务、异步任务、成功失败队列和文件下载',
    primary: '重试失败任务',
    modules: [
      { name: '作业任务', route: '/tskTask/list', object: 'TSK260710-188', actions: ['任务查询', '人工改派', '完成追踪'], api: '/proton/tskTask/list' },
      { name: '任务维护', route: '/tskTask/maintainlist', object: 'TSK-MAINT-260710', actions: ['任务暂停', '恢复执行', '异常关闭'], api: '/proton/tskTask/maintainlist' },
      { name: '异步任务', route: '/asyTask/list', object: 'ASY260710-052', actions: ['队列查询', '执行追踪', '失败重试'], api: '/proton/asyTask/list' },
      { name: '成功任务', route: '/asyTaskSuccess/list', object: 'ASY-SUC-260710', actions: ['成功归档', '结果下载', '链路追踪'], api: '/proton/asyTaskSuccess/list' },
      { name: '失败任务', route: '/asyTaskFail/list', object: 'ASY-FAIL-260710', actions: ['失败定位', '原幂等号重试', '人工处理'], api: '/proton/asyTaskFail/list' },
      { name: '文件下载', route: '/fileDownload/list', object: 'FILE260710-031', actions: ['导出任务', '下载文件', '过期清理'], api: '/proton/fileDownload/list' },
    ],
  },
  {
    id: 'protonSystem',
    eyebrow: 'PROTON SYSTEM',
    title: '系统安全套件',
    desc: '覆盖用户、角色、参数配置、注册和密码找回',
    primary: '安全校验',
    modules: [
      { name: '用户管理', route: '/sysUser/list', object: 'U-WMS-001', actions: ['账号创建', '角色分配', '状态锁定'], api: '/proton/sysUser/list' },
      { name: '角色管理', route: '/sysRole/list', object: 'R-WH-MANAGER', actions: ['角色建模', '权限发布', '职责分离'], api: '/proton/sysRole/list' },
      { name: '系统参数', route: '/sysConfig/list', object: 'CFG-WMS-CORE', actions: ['参数维护', '受控发布', '审计记录'], api: '/proton/sysConfig/list' },
      { name: '注册', route: '/register', object: 'REG-TENANT', actions: ['租户注册', '账号激活', '初始化仓库'], api: '/proton/register' },
      { name: '忘记密码', route: '/forgetPassword', object: 'PWD-RESET', actions: ['身份校验', '重置密码', '登录审计'], api: '/proton/forgetPassword' },
    ],
  },
];

export const protonSuiteById = (id) => protonSuites.find((suite) => suite.id === id);

export const protonModuleByRoute = (route) => {
  for (const suite of protonSuites) {
    const module = suite.modules.find((item) => item.route === route);
    if (module) return { suite, module };
  }
  return null;
};
